apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    tier: redis
  name: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0-alpine
          #command: ["tail", "-f", "/dev/null"]
          resources:
            requests:
              memory: "16M"
          livenessProbe:
            exec:
              command:
              - redis-cli
              - ping
          volumeMounts:
            - mountPath: /data
              name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
